name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JRuby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'jruby-9.4.1.0'
    - name: Install dependencies
      run: bundle install
